modLoader="javafml"
loaderVersion="[28,)" #mandatory 27 = 1.14.3, 28 = 1.14.4
issueTrackerURL="https://github.com/mcenderdragon/PetCollars/issues"
[[mods]]
modId="petcollars"
version="${file.jarVersion}"
displayName="Pet Collars"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pet-collars"
logoFile="petcollars.png" #optional
credits="All the lost dogos" 
authors="MCenderdragon"
description='''
WIth this mod you can add a collar with custom pendants to any animal.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.petcollars]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.petcollars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
